# Generated by Django 3.0 on 2020-10-14 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('tm_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('backdrop_path', models.URLField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('tagline', models.CharField(blank=True, max_length=100, null=True)),
                ('release_date', models.CharField(blank=True, max_length=10, null=True)),
                ('runtime', models.CharField(blank=True, max_length=10, null=True)),
                ('rating', models.CharField(blank=True, max_length=5, null=True)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('poster', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_id', models.CharField(max_length=6)),
                ('title', models.CharField(max_length=50)),
                ('backdrop_path', models.URLField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('create_date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NowMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_id', models.CharField(max_length=6)),
                ('title', models.CharField(max_length=50)),
                ('backdrop_path', models.URLField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=5, null=True)),
                ('release_date', models.CharField(blank=True, max_length=10, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('create_date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SimulaMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simula_id', models.CharField(max_length=6)),
                ('title', models.CharField(max_length=50)),
                ('backdrop_path', models.URLField(blank=True)),
                ('tmdb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simula', to='movie.MovieDetail')),
            ],
        ),
        migrations.CreateModel(
            name='MovieGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backdrop_path', models.CharField(max_length=200)),
                ('tmdb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='movie.MovieDetail')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_name', models.CharField(max_length=50)),
                ('cast_role', models.CharField(max_length=100)),
                ('cast_image', models.URLField(blank=True, null=True)),
                ('tmdb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='movie.MovieDetail')),
            ],
        ),
    ]
