# Generated by Django 3.1 on 2020-09-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecast',
            name='cast_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
