# Generated by Django 3.1 on 2020-09-27 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200927_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviegallery',
            name='tmdb_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='movie.moviedetail'),
        ),
        migrations.AlterField(
            model_name='simulamovie',
            name='tmdb_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simula', to='movie.moviedetail'),
        ),
    ]
